server:
  port: 8081
  servlet:
    context-path: /sharding #项目访问路径
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.142.82:3306/ssm_crud?characterEncoding=utf-8
    username: root
    password: 19971104
