#
#server:
##  port: 8081
#  servlet:
#    context-path: /sharding #项目访问路径
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.120.60:33306/sharding_db?characterEncoding=utf-8
#    username: root
#    password: root
#  application:
#    name: sharding
